import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  alternates: {
    canonical: "/privacy-policy"
  }
};

export default function PrivacyPolicy() {
  return (
    <div>
      <h1 className="text-2xl" itemProp="name">
        Privacy Policy
      </h1>
      <span>Effective date: May 12, 2024</span>
      <div className='mt-4'>
        <div className='mt-4'>
          <div className='pb-3'>
            At <strong>MS-29</strong>, accessible from <Link className="text-blue-600" href='/'>MS-29.com</Link>, one of our main priorities 
            is the privacy of our visitors. This <span className='uppercase'>Privacy Policy</span> contains types of information that is collected 
            and recorded by MS-29 and how we use it.
          </div>
          <div>
            This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information 
            that they shared and/or collect in MS-29.
          </div> 
        </div>
        <div className='mt-4'>
          <strong className="text-lg">Acceptance of Privacy Policy</strong>
        </div>
        <div>
          By accessing or using <Link className="text-blue-600" href='/'>MS-29.com</Link> website, you acknowledge that you have read and understood
          the Privacy Policy. If you do not agree this privacy policy, you should not access or use this site. For further updates of the policy, you
          should consider to revisit the Privacy Policy periodically.
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>Definitions</strong>
        </div>
        <div>
          <div>For the purposes of this Privacy Policy:
            <ul className="list-disc ml-6 pt-1 pl-2.5">
              <li>
                <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
              </li>
              <li>
                <strong>Service</strong> refers to the Website.
              </li>
              <li>
                <strong>Website</strong> refers to MS-29, accessible from <Link className="text-blue-600" href='/' target='_blank'>MS-29.com</Link>
              </li>
              <li>
                <strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to MS-29.
              </li>
              <li>
                <strong>Country</strong> refers to: Bangladesh
              </li>
              <li>
                <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
              </li>
              <li>
                <strong>Personal Information</strong> is any information that relates to an identified or identifiable individual.
              </li>
              <li>
                <strong>Usage Information</strong> refers to data collected automatically, either generated by the use of the Service or
                from the Service infrastructure itself (for example, the duration of a page visit).
              </li>
              <li>
                <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers
                to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf
                of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
              </li>
              <li>
                <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website,
                containing the details of Your browsing history on that website among its many uses.
              </li>
              <li>
                <strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User
                can log in or create an account to use the Service.
              </li>
              <li>
                <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which
                such individual is accessing or using the Service, as applicable.
              </li>
            </ul>
          </div>
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>Information we collect</strong>
        </div>
        <div>
          Information we collect includes both information you knowingly and actively provide us when using or participating
          in any of our services and promotions, and any information automatically sent by your devices in the course of accessing
          our products and services.
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>Personal Information</strong>
        </div>
        <div>
          <div>While using Our Service, We may ask You to provide Us with certain personally identifiable information
            that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </div>
          <ul className="list-disc ml-6 pt-1 pl-2.5">
            <li>First Name</li>
            <li>Last Name</li>
            <li>Email Address</li>
          </ul>
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>Usage Information</strong>
        </div>
        <div>
          <div className='pb-3'>
            When you visit our website, our servers may automatically log the standard data provided by your web browser.
            It may include your device&apos;s Internet Protocol (IP) address, your browser type and version, the pages you visit,
            the time and date of your visit, the time spent on each page, other details about your visit, and technical details
            that occur in conjunction with any errors you may encounter.
          </div>
          <div>
            Please be aware that while this information may not be personally identifying by itself, it may be possible
            to combine it with other data to personally identify individual persons.
          </div>
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>Collection and Use of Information</strong>
        </div>
        <div>
          <div>
            We may collect personal information from you when you do any of the following on our website:
          </div>
          <ul className="list-disc ml-6 pt-1 pl-2.5">
            <li>Use a mobile device or web browser to access our content</li>
            <li>Contact us via email, or on any similar technologies</li>
          </ul>
          <div className="mt-2">
            We may collect, hold, use, and disclose information for the following purposes, and personal information will not
            be further processed in a manner that is incompatible with these purposes:
          </div>
          <ul className="list-disc ml-6 pt-1 pl-2.5">
            <li>To enable you to customise or personalise your experience of our website.</li>
            <li>To contact and communicate with you.</li>
            <li>
              For analytics, market research, and business development, including to operate and improve our website,
              associated applications, and associated social media platforms.
            </li>
            <li>
              For advertising and marketing, including to send you promotional information about our products and services
              and information about third parties that we consider may be of interest to you.
            </li>
            <li>
              To enable you to access and use our website, associated applications, and associated social media platforms.
            </li>
            <li>
              For security and fraud prevention, and to ensure that our sites and apps are safe, secure, and used in line
              with our terms of use.
            </li>
          </ul>
          <div className="mt-2">
            Please be aware that we may combine information we collect about you with general information or research data we
            receive from other trusted sources.
          </div>
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>Security of your Personal Information</strong>
        </div>
        <div>
          <div className='pb-3'>
            When we collect and process personal information, and while we retain this information, we will protect it
            within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure,
            copying, use, or modification.
          </div>
          <div>
            Although we will do our best to protect the personal information you provide to us, we advise that no method
            of electronic transmission or storage is 100% secure, and no one can guarantee absolute data security. We will
            comply with laws applicable to us in respect of any data breach.
          </div>
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>How Long We Keep Your Personal Information</strong>
        </div>
        <div>
          <div className='pb-3'>
            We keep your personal information only for as long as we need to. This time period may depend on what we are using your
            information for, in accordance with this privacy policy. If your personal information is no longer required, we will delete
            it or make it anonymous by removing all details that identify you.
          </div>
          <div>
            However, if necessary, we may retain your personal information for our compliance with a legal, accounting, or reporting
            obligation or for archiving purposes in the public interest, scientific, or historical research purposes or statistical purposes.
          </div>
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>Children&apos;s Privacy</strong>
        </div>
        <div>
          We do not aim any of our products or services directly at children under the age of 13, and we do not knowingly collect personal
          information about children under 13.
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>Use of Cookies</strong>
        </div>
        <div>
          We use &quot;cookies&quot; to collect information about you and your activity across our site. A cookie is a small piece of data that our
          website stores on your computer, and accesses each time you visit, so we can understand how you use our site. This helps us serve
          you content based on preferences you have specified. To know further, you can visit our <Link href='/cookie-policy'>Cookie Policy</Link>.
        </div>
        <div className='mt-4'>
          <strong className='text-lh'>Advertising Partners Privacy Policies</strong>
        </div>
        <div>
          <div className='pb-3'>
            You may consult this list to find the Privacy Policy for each of the advertising partners of MS-29.
          </div>
          <div className='pb-3'>
            Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their
            respective advertisements and links that appear on MS-29, which are sent directly to users&apos; browser. They
            automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of
            their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.
          </div>
          <div>
            Note that MS-29 has no access to or control over these cookies that are used by third-party advertisers.
          </div>
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>Links to Other Websites</strong>
        </div>
        <div>
          <div className='pb-3'>
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed
            to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.
          </div>
          <div>
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </div>
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>Changes to Privacy Policy</strong>
        </div>
        <div>
          Our policies and procedures are under continual review. We may, from time to time, update our privacy policy.
          We will let you know via email prior to the change becoming effective of the Privacy Policy.
          You are advised to review this Privacy Policy periodically for any changes.
          Changes to this Privacy Policy are effective when they are posted on this page.
        </div>
        <div className='mt-4'>
          <strong className='text-lg'>Contact Us</strong>
        </div>
        <div>
          If you have any questions about this Privacy Policy, You can contact us by using <Link className="text-blue-600" href='/contact-us'>this link</Link>.
        </div>
      </div>
    </div>
  ); 
}
